### ISSUE TITLE
在手机上没有办法跑通mobilenet示例

### ISSUE THREAD

**Issue by yichuxue** [mogoweb/wechat-tfjs-core#1]
不好意思发错地方了。

-------------------------------------

在开发者工具上跑  mobilenet示例可以跑通mobilenet示例，但是在手机上不行。一直显示模型识别中。模型已经加载完毕了。
在IOS12上报错：
Unhandled promise rejection <ReferenceError: Can't find variable: performance>

在Android手机上跑，一直显示模型识别中。不会进行下一步。

开发平台：Windows 10
微信开发者工具：Nightly v1.02.1907032

手机型号：MI9
Android：9.0
微信版本号：7.0.5

手机型号：Iphone 8Plus
IOS版本：12.2
微信版本号：7.0.4

**Comment by yichuxue** [comment]
找到原因了，小程序里面不支持：
`performance.now();`
注释，或者换成new Date().getTime() 就可以了

**Comment by mogoweb** [comment]
> 找到原因了，小程序里面不支持：
> `performance.now();`
> 注释，或者换成new Date().getTime() 就可以了

原来如此，我对小程序开发并不是十分精通，所以都是写的很简单的示例，如果有问题，欢迎指出
